In [1]:
import numpy as np # импортируем библиотеку

In [46]:
ar=np.loadtxt(fname='C:/Users/phomi/OneDrive/Documents/lab1_arr.csv', delimiter=';')  # грузим csv-файл

In [47]:
ar  # выводим исходный массив

array([[ 12.,   2.,   3.],
       [  7.,   1.,   5.],
       [  6.,   5., 130.]])

In [39]:
max_ar=np.max(ar)  # находим мин/макс элементы
min_ar=np.min(ar)

1.0

In [41]:
loc_max=np.where(ar==max_ar)  # узнаем где в массиве хранятся мин/макс элементы
loc_min=np.where(ar==min_ar)

(array([2], dtype=int64), array([2], dtype=int64))


In [45]:
ar[loc_max]=min_ar  # меняем местами и выводим результат
ar[loc_min]=max_ar
ar

array([[ 12.,   2.,   3.],
       [  7., 130.,   5.],
       [  6.,   5.,   1.]])